language: php

php:
  - 7.1
  - 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - travis_retry phpenv rehash

script:
  - composer validate
  - ./vendor/bin/phpcs --standard=psr2 -n src/
  - ./vendor/bin/phpspec run
